### PR TITLE
Merge in new content

### PR DESCRIPTION
**Pull request by mOctave**

### CODE REVIEW

**Comment by mOctave** [comment]
We really should figure out how to get the button that does this for you... unless that requires forks?

**Comment by TheGiraffe3** [comment]
I believe it is forking that adds the button.
Realized, though, that you can merge in main on the command line because we're in the same repository: `git merge main`
Might be the best way to operate if a branch isn't in PR?

**Comment by TheGiraffe3** [comment]
Oh, and it looks like this didn't work because it got squashed; the branch still thinks it's two commits behind.

**Comment by mOctave** [comment]
Ugh. Well, I can always try again from the command line...

**Pull request merged**
